In [172]:
import numpy as np 
import pandas as pd
import sklearn

In [173]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [213]:
myarr[2,1]

np.int64(8)

In [175]:
zeroes = np.zeros((2, 5))

In [176]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [177]:
rng = np.arange(10) #give me a range of numbers from 0 to n-1(in this case n = 10)

In [178]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
lspace = np.linspace(1, 4, 10) #gives me 10 evenly spaced numbers between 1 and 4

In [180]:
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [181]:
emp = np.empty((4, 6))

In [182]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60218491e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23038336e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.20161797e-306, 1.60218491e-306],
       [1.78021798e-306, 6.23059726e-307, 1.42418444e-306,
        1.78020033e-306, 8.01089062e-307, 8.34445562e-308]])

In [183]:
emp_like = np.empty_like(lspace)

In [184]:
emp_like

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [185]:
ide = np.identity(45)

In [186]:
ide.shape

(45, 45)

In [187]:
arr = np.arange(99)

In [188]:
arr.reshape(3, 33) #reshape the array to 3 rows and 33 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [189]:
arr = arr.ravel() 

In [190]:
x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [191]:
ar = np.array(x)

In [192]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
ar.sum(axis = 0) #sum of each column

array([12, 15, 18])

In [194]:
ar.sum(axis = 1) #sum of each row

array([ 6, 15, 24])

In [195]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [196]:
ar.flatten() #returns a copy of the array collapsed into one dimension

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [197]:
for item in ar.flat:
    print(item) #iterating through the array using flat

1
2
3
4
5
6
7
8
9


In [198]:
ar.ndim

2

In [199]:
ar.size

9

In [200]:
ar.nbytes

72

In [201]:
OneD = np.array([1, 2, 3, 4, 5])

In [202]:
OneD.argmax()

np.int64(4)

In [203]:
OneD.argsort() #returns the indices that would sort the array

array([0, 1, 2, 3, 4])

In [204]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [205]:
ar.argmax() #returns the indices of the maximum values along an axis

np.int64(8)

In [206]:
ar.argmax(axis = 0) 

array([2, 2, 2])

In [207]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [208]:
ar.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [209]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [210]:
ar2 = ([[1, 9, 3],
       [4, 8, 6],
       [7, 0, 9]])

In [211]:
ar + ar2


array([[ 2, 11,  6],
       [ 8, 13, 12],
       [14,  8, 18]])

In [212]:
ar * ar2

array([[ 1, 18,  9],
       [16, 40, 36],
       [49,  0, 81]])